config/routes.rb
SoundOcean::Application.routes.draw do

  get "playlists/show"

  get "songs/discover"

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  post 'discover/:sc_track_id' => 'songs#discover'
#         new_user_session GET    /users/sign_in(.:format)       devise/sessions#new
#             user_session POST   /users/sign_in(.:format)       devise/sessions#create
#     destroy_user_session DELETE /users/sign_out(.:format)      devise/sessions#destroy
#            user_password POST   /users/password(.:format)      devise/passwords#create
#        new_user_password GET    /users/password/new(.:format)  devise/passwords#new
#       edit_user_password GET    /users/password/edit(.:format) devise/passwords#edit
#                          PUT    /users/password(.:format)      devise/passwords#update
# cancel_user_registration GET    /users/cancel(.:format)        devise/registrations#cancel
#        user_registration POST   /users(.:format)               devise/registrations#create
#    new_user_registration GET    /users/sign_up(.:format)       devise/registrations#new
#   edit_user_registration GET    /users/edit(.:format)          devise/registrations#edit
#                          PUT    /users(.:format)               devise/registrations#update
#                          DELETE /users(.:format)               devise/registrations#destroy
  root :to => "welcome#index"

  get 'game' => 'game#index'

  get '/get_songs' => 'game#get_songs'

  post 'discover/:sc_track_id' => 'songs#discover'

  # get 'test' => 'game#test'

  # get '/new_user' => 'users#index'
  
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  attr_accessible :name, :user_id

  has_and_belongs_to_many :songs
  belongs_to :user
end

app/models/song.rb
class Song < ActiveRecord::Base
  attr_accessible :artist, :discoveries, :genre, :sc_track_id, :title, :discoverer_id, :url

  belongs_to :discoverer, class_name: "User"
  has_and_belongs_to_many :playlists

  after_initialize :init

  def init
		self.discoveries ||= 1
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :recoverable,
  devise :database_authenticatable, :registerable, :omniauthable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :score, :username, :sc_access_token, :provider

  has_many :discoveries, foreign_key: "discoverer_id", class_name: 'Song'
  has_many :playlists

  # validates_presence_of :email
  validates_uniqueness_of :username

  after_initialize :init

	def self.from_omniauth(auth)
		where(auth.slice(:provider, :uid)).first_or_create do |user|
			user.provider = auth.provider
			user.uid = auth.uid
			user.username = auth.info.nickname
			user.sc_access_token = auth.credentials.token
		end
	end

	def self.new_with_session(params, session)
		if session["devise.user_attributes"]
			new(session["devise.user_attributes"], without_protection: true) do |user|
				user.attributes = params
				user.valid?
			end
		else
			super
		end    
	end

	def email_required?
  		super && provider.blank?
	end

	def password_required?
  		super && provider.blank?
	end

	def update_with_password(params, *options)
	  if encrypted_password.blank?
	    update_attributes(params, *options)
	  else
	    super
	  end
	end

	def init
		self.score ||= 0
		if !self.username || self.username.length < 1
			self.username = self.email.split('@')[0]
		end 
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/game_controller.rb
class GameController < ApplicationController

  def index
    if user_signed_in?
    	playlist = current_user.playlists.first

    	if playlist 
    		@songs = playlist.songs
    	else
    		@songs = false
    	end

    @top_users = User.order('score desc limit 5')


    else
    	# redirect_to root_path
    end

  end

  def get_songs
		client = SoundCloud.new(client_id: ENV['SOUND_OCEAN_SC_CLIENT_ID'])

		tracks = client.get('/tracks', genres: params[:genre], filter: 3, order: 'created_at', limit: 50)
		tracks = tracks.select do |track| 
			track['playback_count'] != nil
		end
		tracks = tracks.sort_by {|track| track.playback_count}
		tracks = tracks.map do |track|
				{
					id: track["id"], 
					title: track['title'], 
					artist: track['user']['username'],
					genre: track['genre'],
					created_at: track['created_at'],
					playback_count: track['playback_count'],
					url: track['permalink_url']
				}
		end
		render json: tracks
  end

end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
	
	def all
	    user = User.from_omniauth(request.env["omniauth.auth"])
		    if user.persisted?
		    	flash.notice = "Signed In!"
		     	sign_in_and_redirect user
		    else
					session["devise.user_attributes"] = user.attributes
		     	redirect_to new_user_registration_url
		    end
  	end

	alias_method :soundcloud, :all

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  
  def show
		if user_signed_in?
			playlist = current_user.playlists.first
			if playlist
				@songs = playlist.songs
			end
		else
			redirect_to root_path
		end	  
  end
  
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def discover
    if user_signed_in?
    	song = Song.find_by_sc_track_id(params[:sc_track_id])
      score = current_user.score
      playlist = current_user.playlists.first
      unless playlist
        playlist = current_user.playlists.create name: "#{current_user.username}'s playlist"
      end


    	if song 
    		song.increment(:discoveries)
    		score += 1
        discovered = false
    	else
    		song = current_user.discoveries.create params[:song]
    		score += 10
        discovered = true
    	end

      unless playlist.songs.include? song 
        playlist.songs << song
      end

      current_user.update_attributes score: score 

      resp = {success: 'yay', song: song, user_score: score, dicovered: discovered }

    	render json: resp
    else
      p params
      render json: {success: 'yay', song: params[:song]}
    end
    
  end

end

app/controllers/users_controller.rb
# probably deleteable
class UsersController < ApplicationController

  def index
    
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/views/game/index.html.erb
<div id="user_nav">
  <span id="logo"><%= link_to image_tag("sound_ocean.png", :border => 0), class: "sound_ocean", id: "left-logo" %></span>
	<span id="not-opacity">
	  Exploring as <strong>
    
    <% if user_signed_in? %>
    <strong><%= current_user.username || current_user.email %></strong>.
    <% else %>
    <strong>a GUEST</strong>.
    <% end %>
   | 
	  <%= link_to "Home", root_path %> |
	  <a href="#" id="new-genre" >New Genre</a> |
    <%= link_to "Logout", destroy_user_session_path, method: :delete %> &nbsp;
	  
	</span>
</div>


<div id="game-container"></div>


<div class="aside" id="playlist-menu">
  <ul class="aside-ul" id="playlist-ul">
    <% if @songs %>
      <% @songs.each do |song| %>
        <li><a class="playlist-track" href="<%= song.url %>" target="_blank"><%= song.artist %> - <%= song.title %></a></li>
      <% end %>
    <% else %>
      <li id="no-songs">No Songs! Swim around and discover some!</li>
    <% end %>
    
  </ul>
  <%= link_to "Ocean Jams", playlists_show_path, class: "button-to", id: "ocean-playlist" %>
</div>

<% if user_signed_in? %>

<div class="aside" id="ranking">
  <span id="current-user-score">Current Score&nbsp;&nbsp; <%= current_user.present? ? current_user.score.to_i : 0 %></span>
  <ul class="aside-ul" id="ranking-ul">
    <li id="score-title">Top Discoverers</li>
    <% if @top_users %>
      <% @top_users.each do |user| %>
        <li><%= user.username %> - <%= user.score %></li>
      <% end %>
    <% end %>
  </ul>
</div>

<% end %>

<div id="genre-picker" class="modal">
  <select name="" id="genre-select">
    <option value="folk">Folk</option>
    <option value="rock">Rock</option>
    <option value="pop">Pop</option>
    <option value="indie">Indie</option>
    <option value="childrens">Childrens</option>
    <option value="classical">Classical</option>
    <option value="hip-hop">Hip Hop</option>
    <option value="trance">Trance</option>
    <option value="acoustic">Acoustic</option>
    <option value="jazz">Jazz</option>
    <option value="rap">Rap</option>
    <option value="alternative">Alternative</option>
    <option value="country">Country</option>
    <option value="electronic">Electronic</option>
    <option value="dubstep">Dubstep</option>
    <option value="heavy metal">Heavy Metal</option>
  </select>
  <input type="submit" id="genre-button" class="button-to" value="Pick a genre"/>
</div>

<div id="current-song" class="modal"><span id="current-song-dislay"> 

   You are listening to</span>
   <span id="discovered-song-title" >title</span> by <span id="discovered-song-artist" >artist</span>

  <input type="submit" id="add-button" class="button-to" value="Add to playlist!"/>
  <input type="submit" id="no-thanks" class="button-to" value="No Thanks"/>
</div>

<div id="arrow-keys-modal" class="modal">
  <p>Use the arrow key's to move your avatar</p>
  <p>Use the spacebar for a speed boost</p>
  <p>Navigate offscreen for new discoveries!</p>
</div>

<!-- <div id="spacebar-modal" class="modal"></div>

<div id="navigate-modal" class="modal"></div> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SoundOcean</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <link href='http://fonts.googleapis.com/css?family=Raleway+Dots' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Raleway:300' rel='stylesheet' type='text/css'>
  <script>
    var user_signed_in = <%= user_signed_in?  %>
  </script>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="container"></div>
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, id: "flash_#{name}", class: "error-div" %>
    <% end %>
    <canvas class="world" id="world1"></canvas>
    <canvas class="world" id="world2"></canvas>
    <canvas class="world" id="world3"></canvas>
    <a href="https://soundcloud.com"><img id="sc-logo" src="/assets/sc-logo.png"></a>
    <%= yield %>
</div>
</body>
</html>

app/views/playlists/show.html.erb
<div class="devise-box" id="playlist-box">
<%= link_to image_tag("sound_ocean.png", :border => 0), class: "sound_ocean" %>	
<h1>Your Ocean Sounds Playlists</h1><br />
<%= link_to "Get back in the ocean already!", game_path, class: "button-to", id: "ocean-playlist" %>

	<% @songs.each do |song| %>
		<ul>
			<li class="song-info"><h3><a href="<%= song.url %>" target="_blank" ><%= song.title[0..55] %></a></h3></li>
			<li class="song-info">by <%= song.artist %></li>
		</ul>
	<% end %>
	

</div>

app/views/welcome/index.html.erb
<div id="devise-container">
<div id="welcome-box" class="devise-box">

	<a href="/" class="ajax-butt"><%= image_tag "sound_ocean.png", :border => 0 %></a>

	<h1>Welcome to the Sound Ocean</h1>
	

    <div id="options">
		<% if user_signed_in? %>
			<div class="form-elements">Signed in as <%= current_user.username %>.<br /></div>
			<br />
    		<div class="form-elements"><%= link_to "Get back in the ocean already!", game_path, class: "button-to" %><br /></div>
			<br />
    		<div class="form-elements"><%= link_to "Swim out. Bye-bye.", destroy_user_session_path, method: 'delete', class: "button-to" %><br /></div>
    		
    	<% else %>	
    		<!-- <p><%# link_to image_tag("btn-connect-sc-l.png", :border => 0), user_omniauth_authorize_path(:soundcloud) %></p> -->
			<p><%= link_to "First time at sea? (sign up)", new_user_registration_path, class: "button-to ajax-butt" %></p>
			<p><%= link_to "Dive in! (log in)", new_user_session_path, class: "button-to ajax-butt" %></p>
			<p><%= link_to "Swim as a Guest", game_path, class: "button-to" %></p>
		</div>
		<% end %>
</div>
</div>